- name: NGINX Server
  hosts: web
  become: yes
  tasks:
  - name: Install NGINX
    ansible.builtin.package:
      name: nginx
      status: present
  - name: Enabling NGINX
    ansible.builtin.service:
      name: nginx
      status: started
      enabled: yes