- name: Preference variables
  hosts: local
  connection: local
  vars:
    GREET: "TASK-1"
  # vars_files:
  #   - course.yaml
  # vars_prompt:
  #   - name: GREET
  #     prompt: Enter the value
  #     private: false
  
  tasks:
  - name: print the variable
    # vars:
    #   GREET: "TASK-2"
    ansible.builtin.debug:
      msg: "Hello from {{ GREET }}"

# 1. command line or args
# 2. under task
# 3. files
# 4. prompt
# 5. vars
# 6. inventory file
# 7. roles